#mkdocs serve
site_name: MarkDown_Log
site_url: https://yinzhipeng123.github.io/markdown_log/
repo_name: MarkDown_Log
repo_url: https://github.com/yinzhipeng123/markdown_log/
copyright: MarkDown_Log - Documentation


extra:
  search:
    language: 'jp'

nav:
- Home: index.md
- MkDocs:
  - MkDocs: api/MkDoc.md
- Prometheus:
  - Prometheus:
    - 单机部署: prometheus/prometheus/prometheus.md
    - K8S部署: prometheus/prometheus/prometheus_k8s.md
    - K8S kube-state-metrics指标说明: prometheus/prometheus/kube-state-metrics.md
    - Exporter Metrics解释: prometheus/prometheus/Exporter_Metrics.md
    - Prometheus监控查询例子: prometheus/prometheus/query_xamples.md
    - Prometheus监控查询语法入门: prometheus/prometheus/query_rules.md
    - Prometheus语法函数: prometheus/prometheus/function.md
    - Prometheus recording_rules功能: prometheus/prometheus/prometheus_recording_rule.md
    - Prometheus指标讲解"为什么rate可以计算CPU的使用率": prometheus/prometheus/prometheus_rate.md
  - Alertmanager:
    - Alertmanager部署: prometheus/prometheus/prometheus.md
    - Alertmanager配置: prometheus/alertmanager/alertmanager_config.md
  - Grafana:
    - Grafana部署: prometheus/grafana/grafana_install.md
    - Dashboard: prometheus/grafana/grafana_dashboard.md
    - Grafana添加变量: prometheus/grafana/grafana_var.md
- Etcd:
  - etcd部署: etcd/etcd.md
- Python:
  - CSV模块: python/csv.md
  - XLSX模块: python/xlxs.md
  - K8S模块: python/k8s.md
  - 内存性能模块: python/mem.md
  - Centos7安装Python3: python/python3_env.md
  - Python3 Dokcer镜像制作: python/python3_docker.md
  - Python3 日志控制: python/python_log.md
- Go:
  - Go入门: go/go_one.md
  - Web框架 Gin: 
    - Gin入门:  go/go_gin.md
    - Gin 路由拆分成单个文件: go/gin_route.md
    - Gin 路由拆分成单独APP: go/gin__app_route.md
- KubeSphere:
  - KubeSphere安装: KubeSphere/KubeSphere.md
- Yum:
  - ius源: yum/ius.md
- Centos7:
  - 修改网卡: centos7/ens33.md
- K8S:
  - K8S 1.16.9部署: kubernetes/kubernetes1.16.md


theme:
  name: material
  language: 'zh'
plugins:
  - search:
      indexing: 'full'