#mkdocs serve
site_name: MarkDown_Log
site_url: https://yinzhipeng123.github.io/markdown_log/
repo_name: MarkDown_Log
repo_url: https://github.com/yinzhipeng123/markdown_log/
copyright: MarkDown_Log - Documentation


markdown_extensions:
  - pymdownx.highlight: 
      use_pygments: false
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.keys
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html

extra:
  search:
    language: 'zh_CN'
  disqus: 'something'
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com


theme:
  name: material
  language: 'zh'
  
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono


plugins:
  - search:
      indexing: 'full'
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js
  - javascripts/busuanzi.pure.mini.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/an-old-hope.min.css

nav:
- Home: index.md
- 编程语言:
  - Python:
    - Python一些语法: python/basics/basic.md
    - CSV模块: python/csv.md
    - XLSX模块: python/xlxs.md
    - XLSX转CSV: python/xlsx_to_csv.md
    - K8S模块: python/k8s.md
    - 内存性能模块: python/mem.md
    - Centos7安装Python3: python/python3_env.md
    - Python3 Dokcer镜像制作: python/python3_docker.md
    - Python3 日志控制: python/python_log.md
    - Flask: python/flask/flask_init.md
    - 线程: 
      - 通过继承实现多线程: python/threading/thread.md
      - threading.Event(): python/threading/thread_event.md
      - join的作用: python/threading/join.md
    - shedule:
      - 后台执行: python/shedule/run_in_back.md
      - schedule日志显示下次任务执行时间: python/shedule/see_cron.md
    - 类:
      - 类的继承: python/basics/class/class.md
      - 类变量与实例变量: python/basics/class/class_var.md
    - mypy: python/basics/mypy.md
  - Go:
    - Go入门: go/go_one.md
    - Web框架 Gin: 
      - Gin入门:  go/go_gin.md
      - Gin 路由拆分成单个文件: go/gin_route.md
      - Gin 路由拆分成单独APP: go/gin__app_route.md
- 容器技术:
  - K8S:
    - K8S 1.16.9部署: kubernetes/kubernetes1.16.md
    - 污点: kubernetes/dudian.md
    - 亲和性: kubernetes/diaodu.md
    - minikube: kubernetes/minikube/minikube.md
    - ClusterRole: kubernetes/ClusterRole.md
    - emptyDir: kubernetes/emptyDir.md
    - deployment添加配置文件: kubernetes/configmap-one.md
    - 主机内目录挂载到pod中: kubernetes/hostpath.md
    - statefulset的demo: kubernetes/statefulset.md
  - KubeSphere:
    - KubeSphere安装: KubeSphere/KubeSphere.md
  - Rancher:
    - Rancher安装: rancher/rancher_instatll.md
  - Docker:
    - Docker安装和加速: docker/docker_su.md
    - 停止docker出现警告: docker/docker_Warning.md
    - docker_compose中卷的映射: docker/docker-compose.md
    - docker_compse讲解: docker/pinpoint_compose.md
- 中间件:
  - Etcd:
    - etcd部署: etcd/etcd.md
  - 内网穿透:
    - n2n: n2n/n2n.md
  - Pinpoint:
    - Pinpoint安装: pinpoint/pinpoint_install.md
- 监控:
  - Prometheus:
    - Prometheus:
      - 单机部署: prometheus/prometheus/prometheus.md
      - K8S部署: prometheus/prometheus/prometheus_k8s.md
      - K8S kube-state-metrics指标说明: prometheus/prometheus/kube-state-metrics.md
      - Exporter Metrics解释: prometheus/prometheus/Exporter_Metrics.md
      - Prometheus监控查询例子: prometheus/prometheus/query_xamples.md
      - Prometheus监控查询语法入门: prometheus/prometheus/query_rules.md
      - Prometheus语法函数: prometheus/prometheus/function.md
      - Prometheus recording_rules功能: prometheus/prometheus/prometheus_recording_rule.md
      - Prometheus指标讲解"为什么rate可以计算CPU的使用率": prometheus/prometheus/prometheus_rate.md
  - Alertmanager:
    - Alertmanager部署: prometheus/prometheus/prometheus.md
    - Alertmanager配置: prometheus/alertmanager/alertmanager_config.md
  - Grafana:
    - Grafana部署: prometheus/grafana/grafana_install.md
    - Dashboard: prometheus/grafana/grafana_dashboard.md
    - Grafana添加变量: prometheus/grafana/grafana_var.md
- 操作系统:
  - 汇编基础:
      - win10下搭建8086汇编环境: Linux/汇编/win10-masm.md
  - 计算:
    - 线程: 
      - 什么是线程: Linux/Cpu/线程的研究.md
      - LWP: Linux/Cpu/LWP.md
  - Centos7:
    - 修改网卡: centos7/ens33.md
    - Yum:
        - ius源: yum/ius.md
- 散文:
  - 常用地址: soft/url.md
  - URL在线编码转换工具: soft/url_code.md
  - P99: soft/p99.md
  - github代码对比: soft/github.md
  - MkDocs:
    - MkDocs在Python2环境下的使用: api/MkDoc.md
