#mkdocs serve
site_name: MarkDown_Log
site_url: https://yinzhipeng123.github.io/markdown_log/
# 设置git库 https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_name: MarkDown_Log
repo_url: https://github.com/yinzhipeng123/markdown_log/

markdown_extensions:
#  语法高亮，不使用pygments，设置Highlight.jsw为高亮，参考：https://github.com/squidfunk/mkdocs-material/blob/master/docs/setup/extensions/python-markdown-extensions.md
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences

#  可以在md引用单独的代码段文件，参看使用：https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#adding-a-glossary
  - pymdownx.snippets
#  可以在md中添加键盘图标，参考：https://squidfunk.github.io/mkdocs-material/reference/formatting/#adding-keyboard-keys
  - pymdownx.keys
# 下面三个选项，给md添加关键字，来实现页面上特殊的提示块，参考使用：https://squidfunk.github.io/mkdocs-material/reference/admonitions/#usage
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#  给md文档中的关键字添加页面提示，官网地址：https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
#  通过md给页面添加按钮，图片格式等样式
  - attr_list
#  通过md给页面添加特殊的列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
#  添加脚注，参考：https://squidfunk.github.io/mkdocs-material/reference/footnotes/#configuration
  - footnotes
#   可以设置页面属性的功能
  - meta
# 可以在md中添加html。参考 https://python-markdown.github.io/extensions/md_in_html/
  - md_in_html
extra:
  disqus: 'something'
#  谷歌分析。https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#google-analytics
  analytics:
    provider: google
    property: G-2ZF49ZVQ2M
#  设置页脚
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:yinzhipeng361@tom.com
      name: 给我发送电子邮件
    - icon: fontawesome/brands/github
      link: https://github.com/yinzhipeng123
      name: github


theme:
  name: material
#  设置站点语言
#  官方文档说明：https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/
  language: 'zh'
  features:
    - content.code.annotate
    - content.tabs.link
#   自动隐藏
    - header.autohide
#    启用索引页，也就是介绍页
    - navigation.indexes
#    即时加载
    - navigation.instant
#    导航栏
    - navigation.tabs
#    导航选项卡将锁定在标题下方
    - navigation.tabs.sticky
#   【返回顶部】的按钮
    - navigation.top
#    锚点跟踪
    - navigation.tracking
#    搜索代码块
    - search.highlight
#    搜索结果共享
    - search.share
#    搜索建议
    - search.suggest

  palette:
#    - 主体颜色
#    - 官方文档说明：https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    - scheme: slate
#      导航栏颜色
      primary: indigo
#      点击颜色
      accent: cyan
#     点击切换主题
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
#  设置文章字体
#  官方文档说明：https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
#  配置搜索索引器在为页面生成索引时将使用的策略。如果项目规模较大，并且索引占用大量磁盘空间，则此属性特别有用,参考地址：https://www.mkdocs.org/user-guide/configuration/#configuration-inheritance
      indexing: 'full'
      separator: '[\\s\\u200b\\-]'
      lang:
        - 'en'
extra_javascript:
#highlight.js  cdn获取地址：https://highlightjs.org/download/
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.5.1/build/highlight.min.js
  - javascripts/highlight.js
  - javascripts/busuanzi.pure.mini.js
extra_css:
#设置代码风格：https://github.com/highlightjs/highlight.js/tree/main/src/styles，注意的:是不要忘记在“.css”之前添加“.min”
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.5.1/build/styles/gradient-dark.min.css


nav:
- Home: index.md
- 编程语言:
  - programming_language/index.md
  - Python:
    - Python一些语法: programming_language/python/basics/basic.md
    - CSV模块: programming_language/python/csv.md
    - CSV、列变行、行变列转换: programming_language/python/csv_row_to_col.md
    - XLSX模块: programming_language/python/xlxs.md
    - XLSX转CSV: programming_language/python/xlsx_to_csv.md
    - K8S模块: programming_language/python/k8s.md
    - 内存性能模块: programming_language/python/mem.md
    - Centos7安装Python3: programming_language/python/python3_env.md
    - MAC安装Python3: programming_language/python/MAC环境.md
    - pycharm不能访问github: programming_language/python/pycharm不能访问github.md
    - Python3 Dokcer镜像制作: programming_language/python/python3_docker.md
    - Python3 日志控制: programming_language/python/python_log.md
    - python函数参数: programming_language/python/函数参数.md
    - python装饰器: programming_language/python/装饰器.md
    - python生成器: programming_language/python/生成器.md
    - python迭代器: programming_language/python/迭代器.md
    - lambda函数: programming_language/python/lambda函数.md
    - Flask: programming_language/python/flask/flask_init.md
    - 多进程和多线程: programming_language/python/多进程和多线程.md
    - 线程:
      - thread线程锁: programming_language/python/threading/thread线程锁.md
      - 通过继承实现多线程: programming_language/python/threading/thread.md
      - threading.Event(): programming_language/python/threading/thread_event.md
      - join的作用: programming_language/python/threading/join.md
      - 通过继承实现多线程: programming_language/python/threading/thread.md
    - 协程: programming_language/python/协程/协程.md
    - shedule:
      - 后台执行: programming_language/python/shedule/run_in_back.md
      - schedule日志显示下次任务执行时间: programming_language/python/shedule/see_cron.md
    - 类:
      - 类的继承: programming_language/python/basics/class/class.md
      - 类变量与实例变量: programming_language/python/basics/class/class_var.md
    - mypy: programming_language/python/basics/mypy.md
  - Go:
    - Go入门: programming_language/go/go_one.md
    - Web框架 Gin: 
      - Gin入门:  programming_language/go/go_gin.md
      - Gin 路由拆分成单个文件: programming_language/go/gin_route.md
      - Gin 路由拆分成单独APP: programming_language/go/gin__app_route.md
  - awk:
    - programming_language/awk/index.md
    - 基础语法: programming_language/awk/awk.md
    - 数组: programming_language/awk/awk_array.md
    - 循环控制: programming_language/awk/awk_process_control.md
    - 匹配: programming_language/awk/awk_matching.md
    - 函数: programming_language/awk/awk_function.md
    - 重定向: programming_language/awk/awk_redirect.md
    - awk使用bash变量: programming_language/awk/awk_var.md
    - awk无缓存输出: programming_language/awk/awk_nocache.md
    - awk不打印某列: programming_language/awk/awk_noprint.md
  - Bash:
    - programming_language/bash/index.md
    - 语法:
      - 变量: programming_language/bash/var.md
      - shell读取变量: programming_language/bash/read_var.md
      - 数学运算: programming_language/bash/math.md
      - 判断: programming_language/bash/branch.md
      - if语句: programming_language/bash/if.md
      - case语句: programming_language/bash/case.md
      - for循环: programming_language/bash/for.md
      - while循环: programming_language/bash/while.md
      - until循环: programming_language/bash/until.md
      - 数组: programming_language/bash/array.md
      - 函数: programming_language/bash/function.md
      - 特殊符号: programming_language/bash/special_symbols.md
      - bash的通配符: programming_language/bash/re.md
      - 重定向: programming_language/bash/redirect.md
  - 一些帮助书写Bash脚本的东西:
      - programming_language/bash_help/index.md
      - sed:
        - programming_language/bash_help/sed/index.md
        - 语法: programming_language/bash_help/sed/sed.md
        - sed脚本: programming_language/bash_help/sed/sed_script.md
        - 拓展: programming_language/bash_help/sed/sed_exd.md
      - grep: programming_language/bash_help/re/grep.md
      - 正则表达式: programming_language/bash_help/re/re.md
      - bash的颜色控制: programming_language/bash_help/echo.md
      - bash脚本查看文件指定行: programming_language/bash_help/cat.md
      - bashm脚本命令行选项: programming_language/bash_help/getops.md
      - bash脚本加密: programming_language/bash_help/gzexe.md
      - 控制bash子bash: programming_language/bash_help/mkfifo.md
      - bash中的异常处理: programming_language/bash_help/trap.md
      - 查看系统软件变化: programming_language/bash_help/rpm.md
      - bash批量登录服务器: programming_language/bash_help/sshpass.md
- 容器技术:
  - lxc/index.md
  - K8S:
    - lxc/kubernetes/index.md
    - minikube: lxc/kubernetes/minikube/minikube.md
    - K8S 1.16.9部署: lxc/kubernetes/kubernetes1.16.md
    - 基础概念: lxc/kubernetes/basic.md
    - 污点: lxc/kubernetes/stain.md
    - 亲和性: lxc/kubernetes/dispatch.md
    - ClusterRole: lxc/kubernetes/ClusterRole.md
    - emptyDir: lxc/kubernetes/emptyDir.md
    - deployment添加配置文件: lxc/kubernetes/configmap-one.md
    - 主机内目录挂载到pod中: lxc/kubernetes/hostpath.md
    - Deployment的demo: lxc/kubernetes/depolyment_model.md
    - statefulset的demo: lxc/kubernetes/statefulset.md
    - liveness: lxc/kubernetes/liveness.md
    - readiness: lxc/kubernetes/readiness.md
    - pvc实验: lxc/kubernetes/pvc实验.md
    - K8S部署应用的8项原则: lxc/kubernetes/principle.md
    - 滚动升级中的maxSurge和maxUnavailable: lxc/kubernetes/滚动升级中的maxSurge和maxUnavailable.md
  - KubeSphere:
    - KubeSphere安装: lxc/kubesphere/kubesphere.md
  - Rancher:
    - Rancher安装: lxc/rancher/rancher_instatll.md
  - Docker:
    - Docker安装和加速: lxc/docker/docker_su.md
    - 停止docker出现警告: lxc/docker/docker_Warning.md
    - docker_compose中卷的映射: lxc/docker/docker-compose.md
    - docker_compse讲解: lxc/docker/pinpoint_compose.md
- 中间件:
  - middleware/index.md
  - Etcd:
    - etcd部署: middleware/etcd/etcd.md
  - 内网穿透:
    - n2n: middleware/n2n/n2n.md
  - Pinpoint:
    - Pinpoint安装: middleware/pinpoint/pinpoint_install.md
  - Mysql:
    - 基本语法: middleware/mysql/basic.md
    - 数据类型: middleware/mysql/type.md
    - 约束: middleware/mysql/constraint.md
    - 授权: middleware/mysql/grant.md
    - 查询: middleware/mysql/select.md
    - 函数: middleware/mysql/function.md

- 监控:
  - monitor/index.md
  - Prometheus:
    - 单机部署: monitor/prometheus/prometheus.md
    - K8S部署: monitor/prometheus/prometheus_k8s.md
    - K8S kube-state-metrics指标说明: monitor/prometheus/kube-state-metrics.md
    - Exporter Metrics解释: monitor/prometheus/Exporter_Metrics.md
    - Prometheus监控查询例子: monitor/prometheus/query_xamples.md
    - Prometheus监控查询语法入门: monitor/prometheus/query_rules.md
    - Prometheus语法函数: monitor/prometheus/function.md
    - Prometheus recording_rules功能: monitor/prometheus/prometheus_recording_rule.md
    - Prometheus指标讲解"为什么rate可以计算CPU的使用率": monitor/prometheus/prometheus_rate.md
  - Alertmanager:
    - Alertmanager部署: monitor/prometheus/prometheus.md
    - Alertmanager配置: monitor/alertmanager/alertmanager_config.md
  - Grafana:
    - Grafana部署: monitor/grafana/grafana_install.md
    - Dashboard: monitor/grafana/grafana_dashboard.md
    - Grafana添加变量: monitor/grafana/grafana_var.md
- 操作系统:
  - Linux:
    - system/index.md
    - 计算相关:
        - 什么是线程: system/linux/计算/线程的研究.md
        - LWP: system/linux/计算/LWP.md
        - 进程间通信: system/linux/计算/进程间通信.md
        - 僵尸进程: system/linux/计算/僵尸进程.md
        - 孤儿进程: system/linux/计算/孤儿进程.md
        - 中断: system/linux/计算/中断.md
        - load高的原因: system/linux/计算/load高的原因.md
        - 上下文切换导致sys高: system/linux/计算/上下文切换导致sys高.md
        - perf命令: system/linux/计算/perf.md
        - vmstat命令: system/linux/计算/vmstat.md
        - ps命令: system/linux/计算/ps.md
        - iostat命令: system/linux/计算/iostat.md
        - sar命令: system/linux/计算/sar.md
        - top命令: system/linux/计算/top.md
        - /proc/stat: system/linux/计算/0proc0stat.md
        - strace命令: system/linux/计算/strace.md
    - 内存相关:
        - 内存: system/linux/内存/内存.md
        - Linux的两种内存分配方式: system/linux/内存/Linux的两种内存分配方式.md
        - 内存回收的方式: system/linux/内存/内存回收的方式.md
        - slabtop命令: system/linux/内存/slabtop.md
        - /proc/slabinfo: system/linux/内存/0proc0slabinfo.md
        - /proc/meminfo: system/linux/内存/0proc0meminfo.md
        - 内存页的理解: system/linux/内存/内存页的理解.md
        - min_free_kbytes参数: system/linux/内存/min_free_kbytes参数.md
        - oom机制: system/linux/内存/oom机制.md
        - oom评分是如何算出来: system/linux/内存/oom评分是如何算出来的.md
        - 计算oom评分的脚本: system/linux/内存/计算oom评分的脚本.md
        - free命令: system/linux/内存/free.md
        - 内存优化的手段: system/linux/内存/内存优化的手段.md
        - 查看进程swap使用的脚本: system/linux/内存/查看进程swap使用的脚本.md
        - 过度分配的理解: system/linux/内存/过度分配的理解.md
    - IO相关:
        - 内核参数: system/linux/IO/内核参数.md
        - proc文件系统: system/linux/IO/0proc文件系统.md
        - sys文件系统: system/linux/IO/0sys文件系统.md
        - IO技术栈: system/linux/IO/IO技术栈.md
        - IO指标及工具: system/linux/IO/IO指标及工具.md
        - IO优化建议: system/linux/IO/IO优化建议.md
        - IO scheduler: system/linux/IO/IO scheduler.md
        - IO的类型: system/linux/IO/IO的类型.md
        - blktrace命令: system/linux/IO/blktrace命令.md
        - hdparm命令: system/linux/IO/hdparm命令.md
        - dumpe2fs: system/linux/IO/dumpe2fs.md
        - iostat: system/linux/IO/iostat.md
        - iotop: system/linux/IO/iotop.md
        - Python导致IO慢案例: system/linux/IO/Python导致IO慢案例.md
        - SQL查询慢案例: system/linux/IO/SQL查询慢案例.md
        - IO测试方法: system/linux/IO/IO测试方法.md

    - 网络相关:
        - TCP图解: system/linux/网络/tcp.md
        - TIME_WAIT过多的解决方法: system/linux/网络/time_wait.md
        - 阿里云修改TCP的TIME-WAIT超时时间: system/linux/网络/修改TCP的TIME-WAIT超时时间.md
        - Linux修改TCP的TIME-WAIT超时时间: system/linux/网络/net.ipv4.tcp_fin_timeout.md
        - 模拟一次CLOSE_WAIT: system/linux/网络/模拟一次.md
        - tcpdump: system/linux/网络/tcpdump.md
        - netstat: system/linux/网络/netstat命令.md
        - 测试TCP带宽: system/linux/网络/测试网络带宽.md
  - Centos7:
    - 修改网卡: system/centos7/ens33.md
    - Yum:
        - ius源: system/centos7/yum/ius.md
    - 时间同步chrony: system/centos7/chronyd.md
  - 虚拟机安装Windows: system/windows/虚拟机安装windows.md
  - 汇编基础:
      - win10下搭建8086汇编环境: system/汇编/win10-masm.md
      - 存储单元: system/汇编/存储单元.md
      - 地址总线: system/汇编/地址总线.md
      - 控制总线: system/汇编/控制总线.md
      - 数据总线: system/汇编/数据总线.md
      - 内存地址空间: system/汇编/内存地址空间.md
      - 8086CPU: system/汇编/8086CPU.md
      - debug命令: system/汇编/debug命令.md
      - 寄存器: system/汇编/寄存器.md
      - 代码段: system/汇编/代码段.md
      - 汇编指令合集: system/汇编/汇编指令合集.md
- 工具:
  - tool/index.md
  - git及github的轻度教程: tool/github使用.md
  - Pycharm及配合Github的使用: tool/pycharm.md
  - MkDocs的使用: tool/MkDoc.md
- 散文:
  - 常用地址: soft/url.md
  - URL在线编码转换工具: soft/url_code.md
  - P99: soft/p99.md
  - github代码对比: soft/github.md


