apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-prometheus-yml
  namespace: default
data:
  prometheus.yml: >-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
    rule_files:

    scrape_configs:
      - job_name: 'prometheus'
        consul_sd_configs:
        - server: 'infra-consul-net:8500'
          services: []
        relabel_configs:
          - source_labels: [__meta_consul_service]
            regex: .*prometheus.*
            action: keep
          - regex: __meta_consul_service_metadata_(.+)
            action: labelmap

      - job_name: 'node-exporter'
        consul_sd_configs:
        - server: 'infra-consul-net:8500'
          services: []
        relabel_configs:
          - source_labels: [__meta_consul_service]
            regex: .*node-exporter.*
            action: keep
          - regex: __meta_consul_service_metadata_(.+)
            action: labelmap

      - job_name: 'kube-state-metrics'
        consul_sd_configs:
        - server: 'infra-consul-net:8500'
          services: []
        relabel_configs:
          - source_labels: [ __meta_consul_service ]
            regex: .*kube-state-metrics.*
            action: keep
          - regex: __meta_consul_service_metadata_(.+)
            action: labelmap