apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infra-consul
    version: infra-consul-uat-podname
  name: infra-consul
  namespace: default
spec:
  selector:
    matchLabels:
      app: infra-consul
  template:
    metadata:
      labels:
        app: infra-consul
    spec:
      containers:
      - name: infra-consul
        image: 'consul:latest'
        env:
          - name: HASHICORP_RELEASES
            value: 'https://releases.hashicorp.com'
          - name: ENV
            value: UAT
        ports:
        - containerPort: 8300
          name: one
          protocol: TCP
        - containerPort: 8301
          name: two
          protocol: TCP
        - containerPort: 8301
          name: three
          protocol: UDP
        - containerPort: 8302
          name: four
          protocol: TCP
        - containerPort: 8302
          name: five
          protocol: TCP
        - containerPort: 8500
          name: six
          protocol: TCP
        - containerPort: 8600
          name: seven
          protocol: UDP

