apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-kube-state-metrics
  namespace: default
  labels:
    app: infra-kube-state-metrics
    version: infra-kube-state-metrics-uat-podname
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: infra-kube-state-metrics
  template:
    metadata:
      labels:
        app: infra-kube-state-metrics
        version: infra-kube-state-metrics-uat-podname
    spec:
      containers:
      - name: my-kube-state-metrics
        image: quay.io/coreos/kube-state-metrics:v1.9.5
        args:
          - '--host=0.0.0.0'
          - '--port=8055'
          - '--telemetry-host=0.0.0.0'
          - '--telemetry-port=8056'

        #设置IP，POD_Name变量
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ENV
            value: UAT
        ports:
        - name: requestshttpone
          containerPort: 8055
          protocol: TCP
        - name: requestshttptwo
          containerPort: 8056
          protocol: TCP
      - name: curl
        image: curlimages/curl:latest
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ENV
            value: UAT
        command: [ '/bin/sh','-c' ]
        args: ['while true;do sleep 1s;done']
        lifecycle:
          postStart:
            exec:
              command: [ '/bin/sh','-c','curl -X PUT -d  "{\"id\": \"kube-state-metrics-$MY_POD_IP\",\"name\": \"kube-state-metrics\",\"address\":\"$MY_POD_IP\",\"port\": 8055,\"tags\": [\"kube-state-metrics\"],\"checks\": [{\"http\": \"http://$MY_POD_IP:8055/metrics\", \"interval\": \"15s\"}]}" http://infra-consul-net:8500/v1/agent/service/register' ]
          preStop:
            exec:
              command: [ '/bin/sh','-c','curl -X PUT http://infra-consul-net:8500/v1/agent/service/deregister/kube-state-metrics-$MY_POD_IP' ]
      serviceAccountName: kube-state-metrics

