apiVersion: v1
kind: Service
metadata:
  name: infra-prometheus-net
  namespace: default
  labels:
    app: infra-prometheus-net
    service: zkh-infra-prometheus-net
spec:
  type: ClusterIP
  ports:
    - name: requestshttp
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: infra-prometheus

